codebase: vg
# ALL AVAILABLE VOICES (so far)
# 'us-clb' - US Female (Nitech ARCTIC)
# 'us-slt' - US Female (Nitech ARCTIC; Midwestern)
# 'us-rms' - US Male (Nitech ARCTIC)
voices:
  # Feminine voiceset
  fem:     us-clb
  # Masculine voiceset
  mas:     us-rms
  # Non-AI announcements (like vox_login, etc)
  default: us-clb
phrasefiles:
  - announcements.txt
  - vg-chemistry.txt
  - voxwords.txt
overrides:
  '.':
    flags:
      #- old-vox
      - no-process
      - no-trim
    #duration: 0.431202
    #word-count: 1
  ',':
    flags:
      #- old-vox
      - no-process
      - no-trim
    #duration: 0.248889
    #word-count: 1
  _bloop:
    flags:
      - old-vox
      - no-process
    duration: 0.609342
    word-count: 1
  _bizwarn:
    flags:
      - old-vox
      - no-process
    duration: 0.888435
    word-count: 1
  _buzwarn:
    flags:
      - old-vox
      - no-process
    duration: 0.781224
    word-count: 1
  _doop:
    flags:
      - old-vox
      - no-process
    duration: 1.145669
    word-count: 1
  _dadeda:
    flags:
      - old-vox
      - no-process
    duration: 0.887982
    word-count: 1
  _woop:
    flags:
      - old-vox
      - no-process
    duration: 0.630295
    word-count: 1
