codebase: vg
# ALL AVAILABLE VOICES (so far)
# 'us-slt' - US Female (Nitech ARCTIC)
# 'us-rms' - US Male (Nitech ARCTIC)
voices:
  # Feminine voiceset
  fem:     us-slt
  # Masculine voiceset
  mas:     us-rms
  # Non-AI announcements (like vox_login, etc)
  default: us-slt
phrasefiles:
  - announcements.txt
  - voxwords.txt
